### ISSUE TITLE
box label transformation should also handle folders that are top containers

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/aspace_helpers#239]
Which of the label transformations is this? An example component would be helpful as well.

**Comment by regineheberlein** [comment]
@faithc

**Comment by faithc** [comment]
Hi @regineheberlein. To clarify, staff have come across issues with both the box and folder label scripts. Not sure if you'll want to create another ticket to differentiate, but re: box labels, labels for oversize folders are not being created. I can check in with ADAPT folks to see if this is actually an issue since staff have been creating these labels manually due to the fact that we're including information in Locations Note field, for example, "B-South 7, Drawer 5." Unless there's a way to add this info programmatically for top containers that are folders? A finding aid that has a couple of (oversize) folders as top containers is C0511.

Re: folder labels, in cases where a component/archival object has an oversize folder or DO instance _in addition_ to a box instance, folder labels say "Multiple Items" and display the title twice in small font. See for example the folder labels that generate for C0511_c0000030 (box + oversize folder) and C0187_c03265 (box + DO). 

Thanks for looking into this!

**Comment by regineheberlein** [comment]
Thanks for the clarification @faithc -- since this affects two separate processes, I'll open a new ticket for the second one.

**Comment by regineheberlein** [comment]
@faithc About oversize folders used as top containers, is there a clear way for the script to know that they are top containers, e.g. a barcode?

**Comment by faithc** [comment]
Oversize folders associated with Resource records in the mss repo do have barcodes, but @LynnDurgin informed me that folders at Mudd do not (though they plan to add these in the future), so I'm not sure there is a clear way to differentiate them. I guess there isn't currently a way to identify top containers in the data that aspace exports? :/  

Again, this might actually be a non issue since I think the use of oversize folders, at least on the Firestone side, isn't super common so we can continue to create these manually. Unless the situation is different for collections at Mudd, @LynnDurgin ?

**Comment by regineheberlein** [comment]
Those transformations run over the EAD output, which may not have all the information that ASpace knows about a container, either. I'm looking at the EAD for C0511, and I can't even identify what would be an oversize folder--can you point me to an example that's currently on production (a real-life example, in other words, not a fake one, just so we're sure we know what the script might have to work with)?

**Comment by regineheberlein** [comment]
Also, for which of the 3 box label transformations currently in SVN are you reporting this behavior?

RBSC_BoxLabels_AbID.xsl
aspace_BoxLabels.xsl
aspace_BoxLabels_2x4.xsl

**Comment by LynnDurgin** [comment]
Yes, @faithc , the creation of oversize folders is a fairly unique occurrence at Mudd and producing labels manually would not be overly burdensome. @regineheberlein Here is an example from the UA repo: /repositories/4/archival_objects/597784

**Comment by faithc** [comment]
> 

RBSC_BoxLabels_AbID.xsl

This is the only script ADAPT will be using from now on for box labels. I had spoken with @Will-Clements about renaming this to aspace_BoxLabels.xsl for simplification.

**Comment by faithc** [comment]
> Also, for which of the 3 box label transformations currently in SVN are you reporting this behavior?
> 
> RBSC_BoxLabels_AbID.xsl aspace_BoxLabels.xsl aspace_BoxLabels_2x4.xsl

RBSC_BoxLabels_AbID.xsl

This is the only script ADAPT will be using from now on for box labels. I had spoken with @Will-Clements about renaming this to aspace_BoxLabels.xsl for simplification.

**Comment by regineheberlein** [comment]
Thanks for the examples. It looks like we're exporting the container profile in `@encodinganalog`, so I'll test for its presence.

**Comment by regineheberlein** [comment]
@LynnDurgin this is fixed for the use case you provided.

@faithc I can't find c18954-76253 in the EAD or in ASpace. If it doesn't work for your use case, we can open a new ticket.

**Comment by faithc** [comment]
> @LynnDurgin this is fixed for the use case you provided.
> 
> @faithc I can't find c18954-76253 in the EAD or in ASpace. If it doesn't work for your use case, we can open a new ticket.

C0511_c18954-76253 is https://aspace.princeton.edu/staff/resources/3737#tree::archival_object_1458119.

**Comment by faithc** [comment]
So the script is creating labels now for oversize folders?
