### ISSUE TITLE
newly created AC107.xx containers missing from staging

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/aspace_helpers#350]
@phoebeno 
In linking the new containers on staging, I've come across a number that appear to have been deleted. It's only staging, so no consequences, I'm just wondering whether that seems familiar to you? So we don't run into any surprises when we run it on prod.

These are the ones that are missing:

barcode
32101104566508
32101104566813
32101104566870
32101104566920
32101104566938
32101104569817
32101104571425
32101104571433
32101104572613
32101104573736
32101104574122
32101104574221
32101104574536

**Comment by phoebeno** [comment]
Hi @regineheberlein thank you! These barcodes are all associated with existing containers on prod. The numbers make sense to me, because they were boxes that already had containers in FAs that had been added at some point by hand. Does that make sense at all. Will the process work, as long as these barcodes do exist in ASpace production now?

**Comment by regineheberlein** [comment]
Oh, I see! Ok, thanks for clarifying! I'll make sure we check for existing containers so we don't link them twice.
